version: '3.8'

services:
  frontend:
    build: ./ui
    container_name: ui
    ports:
      - "80:80"
    # depends_on:
    #   - fintech-api

    # fintech-api:
    #   build: ./api
    #   container_name: fintech-api
    #   ports:
    #     - "80:81"

    # fintech-db:
    #   build: ./mysql
    #   container_name: fintech-db
    #   ports:
    #     - "3306:3306"

volumes:
  db-data:
