version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  php-api:
    build: ./api
    container_name: php-api
    depends_on:
      - mysql
    ports:
      - "8000:80"

  frontend:
    build: ./ui
    container_name: ui
    ports:
      - "8080:80"
    depends_on:
      - php-api

volumes:
  db-data:
